### ISSUE TITLE
NiceToHave: Add a extra header with name of databus connection

### ISSUE THREAD

**Issue by JSCProjects** [Particular/NServiceBus.DataBus.AzureBlobStorage#125]
It would be nice to configure a name when you configure the databus. This can be used with servicepulse and serviceinsight to resolve databus properties

**Comment by JSCProjects** [comment]
Yeah sorry for the short description. Hopefully this describes it better.

When a message is sent with a databus property it would be nice to also configure a name of the connectionstring in the header. This name can be used to find the correct connectionstring inside (to be build) ServiceInsight & ServicePulse addin and then show the real databus property.

**Comment by SeanFeldman** [comment]
@JSCProjects, is this a hypothetical feature or is this what you do today when reviewing failed messages in Service Pulse and messages in Service Insight? Messages that are sent using a data bus contain a header that points to the destination blob. No connection string. Since all the endpoints are supposed to have access to the data bus, that connection string is well known. The same applies to the storage container. Could you highlight what pain point would having a connection string embedded in the headers would sole? Thank you.

**Comment by JSCProjects** [comment]
Security wise imho, but you are also correct that the databus storage connectionstring is the same for our complete environment

**Comment by SeanFeldman** [comment]
> Security wise imho

Security-wise, having a connection string embedded in the message header is less secure 🙂

**Comment by danielmarbach** [comment]
@JSCProjects Given that you mentioned the databus connection string is the same for your complete environment is this issue then a suggestion to have first-class database support in ServiceControl/ServicePulse/ServiceInsight so that you can peak into the content of the message even if it contains databus properties?

**Comment by danielmarbach** [comment]
I raised https://github.com/Particular/ServiceControl/issues/2203
