### ISSUE TITLE
Issue warning when large set of blobs to clean up

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.DataBus.AzureBlobStorage#13]
Connects to https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/issues/14

Notify when the set of blobs becomes very large

**Comment by SeanFeldman** [comment]
How a requirement "set becomes very large" can be quantified? Is it more than a thousand, 10K, 100K?

**Comment by yvesgoeleven** [comment]
@wettsten instead of computing such a value. if we'd just prevent concurrent runs, using a semaphore or such, and make it configurable would that be good as well?

**Comment by SeanFeldman** [comment]
Very much connected to #12. Since based on implementation of #12, this one could be addressed (i.e. log a warning when cleanup takes longer than a configured threshold).

**Comment by wettsten** [comment]
@yvesgoeleven i was just thinking of that this morning. concurrent runs would be pointless.

**Comment by SeanFeldman** [comment]
With the current design concurrent runs will also happen when an endpoint is scaled out 😞

**Comment by yvesgoeleven** [comment]
@SeanFeldman we can use a lease blob instead

**Comment by wettsten** [comment]
this issue could be mitigated by each endpoint maintaining its own container or folder within a shared container. the problem that i run into is when a subscriber subscribes to two different endpoints, each with its own container, it can't use the message header to load the correct container. instead, it looks in the container defined by its own configuration. the container and base path in the databus settings should only be used in outgoing messages so that it can be flexible for incoming messages.

**Comment by SeanFeldman** [comment]
@wettsten each endpoint having its own container is not enough. Each endpoint can be scaled out, which will cause instances (of the same endpoint) to run in parallel when trying to delete blobs.

BTW, you can use a `container` per endpoint (https://docs.particular.net/nservicebus/messaging/databus/azure-blob-storage), but it won't solve the issue with multiple instances.

Created a new overarching issue ( #14 ) where we'll discuss a better way to address it.
Thank you for your valuable feedback 😃

**Comment by danielmarbach** [comment]
Closing reason see https://github.com/Particular/NServiceBus.DataBus.AzureBlobStorage/issues/14#issuecomment-343955495
